  - curl --no-progress-meter --fail-with-body --remove-on-error --location --output /usr/local/bin/b2 https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux
  - chmod +x /usr/local/bin/b2
