  - gpg --batch --generate-key ${vault_gpg_key_conf_file_full_path}
  - gpg --armor --output ${vault_pgp_pub_key_full_path} --export ${vault_gpg_key_name}
  - gpg --armor --export-options backup --output ${vault_pgp_priv_key_full_path} --export-secret-keys ${vault_gpg_key_name}
