  - _OS_ID=$(cat /etc/os-release | grep ^ID= | sed 's/ID=//' | sed 's/"//g' | sed 's/-/_/g')
  - ubuntu="apt-get --yes"
  - debian="apt-get --yes"
  - sles="zypper --non-interactive"
  - opensuse_leap="zypper --non-interactive"
  - eval cmd=\$$_OS_ID
  - $cmd install ${packages}
